### ISSUE TITLE
Disable/ Delete text for "Smart Home Monitor"

### ISSUE THREAD

**Issue by tuhinz** [rayzurbock/SmartThings-BigTalker#10]
Big Talker P.2.0.a6 / C.2.0.a6:

I have an issue with the "Smart Home Monitor" text field which shows default text as "Smart Home is now armed in XX mode". If i change the field to blank (Shows "Tap to set"), next time it reverts to the same value in the text field. As far as i can tell, the actual value still stays blank but its misleading to see the default text in  the text field rather than "Tap to Set".  I believe this issue is also present in the release version of BT.

**Comment by rayzurbock** [comment]
I believe I have this corrected in P2.0.a7 /C.2.0a7.
Update via GitHub integration or by copy/paste of the parent/child raw code.
Publish the parent and save the child.

**Comment by tuhinz** [comment]
Updated to 2.0.a.7 for both parent and child- still have the same issue. Even if i specifically delete the SHM spoken text, next time i enter the SHM settings, the text field shows the default text.

**Comment by rayzurbock** [comment]
When you first configure speech for a device type (switch, motion, etc), the BigTalker GUI inserts a default phrase for the events associated with that device (Switch = On and Off events, Motion = Active and Inactive events, etc).  This is based on what the user is likely to use and to give an example upfront of how to use the `%devicename%`, `%devicechange%`, etc variables/tokens. This is by design for user friendliness. The "Tap to set" indicates it hasn't been set yet.  "Tap to modify" indicates that you have configured phrases for that device type within the group that you are in.

If you configure a device type in a group and only set one of the available event types (ON or OFF for a switch) and delete the text for the other event type you will find that the deletion of text for that event stays removed.  If you remove the phrase for all events for that device then you will find that the event will show "Tap to set" and will contain the default text when you choose to configure it.  If you back out "<" and do not click "Done" then the default text displayed does not get set as the desired phrase.

**Comment by rayzurbock** [comment]
See previous note (10/6/2017).
This is by design.  Default text is inserted when you open an unconfigured event which is indicated by the event type showing "Tap to set".  This is primarily for user friendliness. Once "Tap to set" is pressed, the phrase shown gives an example of a commonly used phrase for the event type allowing the user to modify or just hit Done configuring the event an using the example phrase as-is.  Once an event is configured the text for that event changes from "Tap to set" to "Tap to modify".
